baseURL = "https://ptorras.github.io"
title = "Pau Torras"
languageCode = "en-us"
theme = "personal"
pagination.pagerSize = 5
copyright = "Pau Torras"

[params]
  subtitle = "A place where I write about my ongoing research and other endeavours."
  description = "A place where I write about my ongoing research and other endeavours."
  copyright = "Pau Torras"
  dateFormat = "2006-01-02"
  showReadingTime = true
  mainSection = "posts"
  postsOnHomePage = 5
  rss = false

[[menu.main]]
  name = "About Me"
  url = "/resume"
[[menu.main]]
  name = "Blog"
  url = "/posts"
[[menu.main]]
  name = "Teaching & Talks"
  url = "/teaching/"
[[menu.main]]
  name = "Music Practice"
  url = "/music-practice/"

[markup]
  [markup.highlight]
    noClasses = false
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        disable = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
