baseurl = "https://ptorras.github.io"
title = "Pau Torras"
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-cactus"
copyright = "Pau Torras"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Thoughts"
url = "./posts"
weight = 2

[[menu.main]]
name = "About"
url = "./resume"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = false
  mainSectionTitle = "Thoughts"

  showAllPostsArchive = true # default
  tocInline = true
  mathjax = true

  # Home page settings
  description = "A place where I write about my ongoing research and other endeavours."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ptorras"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/RostarFreeman"
  [[params.social]]
    name = "scholar"
    link = "https://scholar.google.es/citations?user=38hJaFgAAAAJ&hl=ca"
  [[params.social]]
    name = "soundcloud"
    link = "https://soundcloud.com/rostarfreeman"
  [[params.social]]
    name = "email"
    link = "ptorras <at> cvc.uab.cat"